GET http://localhost:3000/alunos
Content-Type: application/json

###
GET http://localhost:3000/alunos/5cd0fc9ff9a0ef7488e426be
Content-Type: application/json

###
POST http://localhost:3000/alunos
Content-Type: application/json

{
  "cursoId": "",
  "nome": "Matheus Manhães",
  "dataNascimento": "06/02/1995",
  "matriculaAtiva": "5306368",
  "estadoCivil": "Solteiro",
  "matricula": "5306369",
  "telefone": ["99557-5991"],
  "idade": "22"
}

###
DELETE http://localhost:3000/alunos/5cd0fcb3f9a0ef7488e426bf
