GET http://localhost:3000/alunos
Content-Type: application/json

###
GET http://localhost:3000/alunos/5cd1021ab529381dec750084
Content-Type: application/json

###
POST http://localhost:3000/alunos
Content-Type: application/json

{
  "cursoId": "5cd101cdc4c9bf071cc3885c",
  "nome": "Matheus Genteluci",
  "dataNascimento": "06/02/1997",
  "matriculaAtiva": "5306369",
  "estadoCivil": "Solteiro",
  "matricula": "5306369",
  "telefone": ["99557-5991"],
  "idade": "22"
}

###
DELETE http://localhost:3000/alunos/5cd0fcb3f9a0ef7488e426bf
