GET http://localhost:3000/cursos

###
GET http://localhost:3000/cursos/Medicina

###
POST http://localhost:3000/cursos
Content-Type: application/json

{
  "nome": "Direito"
}

###
PUT http://localhost:3000/cursos/5cd1082e7db98d7a546a6036
Content-Type: application/json

{
  "nome": "Administração"
}

###
DELETE http://localhost:3000/cursos/5cd105c0d7d50d58e00397c8
Content-Type: application/json